# For more see: https://github.com/actions/labeler?tab=readme-ov-file#pull-request-labeler
MCMC:
  - changed-files:
      - any-glob-to-any-file: 
          - Fitters/**

Plotting:
  - changed-files:
      - any-glob-to-any-file: 
          - Plotting/**
          - Diagnostics/**

Nu Osc/Xsec:
  - changed-files:
      - any-glob-to-any-file: 
          - Parameters/**
          - Splines/**

Samples:
  - changed-files:
      - any-glob-to-any-file: 
          - Samples/**

Manager:
  - changed-files:
      - any-glob-to-any-file: 
          - Manager/**

Documentation:
  - changed-files:
      - any-glob-to-any-file: 
          - Doc/**
Cmake:
  - changed-files:
      - any-glob-to-any-file:
          - cmake/**
          - CMakeLists.txt

GPU:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.cu'
          - '**/*.cuh'

CI/CD:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**

python:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.py'

