# .github/release.yml

changelog:
  categories:
    - title: 🏕 Features
      labels:
        - '*'
      exclude:
        - dependencies
        - Tidy

    - title: 🧹 Tidy
      labels:
        - Tidy
      exclude:
        - dependencies

    - title: 👒 Dependencies
      labels:
        - dependencies
      exclude:
        - Tidy
