#KS: Inspired by Nuisance code
if(NOT COMMAND DefineEnabledRequiredSwitch)
  function(DefineEnabledRequiredSwitch VARNAME DEFAULTVALUE)
    if(NOT DEFINED ${VARNAME} OR "${${VARNAME}}x" STREQUAL "x")
      set(${VARNAME} ${DEFAULTVALUE} PARENT_SCOPE)
      set(${VARNAME} ${DEFAULTVALUE})
    else()
      set(${VARNAME}_REQUIRED ${${VARNAME}} PARENT_SCOPE)
      set(${VARNAME}_REQUIRED ${${VARNAME}})
    endif()
  endfunction()
endif()

#KS: Some cmake use 0 or 1 instead of true/false, weird I know. This simple tool will translate it for us
if(NOT COMMAND IsTrue)
  function(IsTrue VAR RESULT)
    if(NOT DEFINED ${VAR} OR NOT ${${VAR}})
      set(${RESULT} 0 PARENT_SCOPE)
    else()
      set(${RESULT} 1 PARENT_SCOPE)
    endif()
  endfunction()
endif()

#KS: Change TRUE to FALSE etc.
if(NOT COMMAND SwitchLogic)
  function(SwitchLogic VAR)
    if(${VAR} STREQUAL "TRUE")
      set(${VAR} "FALSE" PARENT_SCOPE)
    elseif(${VAR} STREQUAL "FALSE")
      set(${VAR} "TRUE" PARENT_SCOPE)
    elseif(${VAR} STREQUAL "0")
      set(${VAR} "1" PARENT_SCOPE)
    elseif(${VAR} STREQUAL "1")
      set(${VAR} "0" PARENT_SCOPE)
    endif()
  endfunction()
endif()
