---
# Performs unit and integration testing
name: Validations Python CI 

## The events that trigger the workflow
on:
  pull_request:
    branches: [ develop ]

  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/mach3-software/mach3:alma9latest

    steps:

    - name: Get MaCh3 Validations
      run: |
        cd /opt/
        git clone https://github.com/mach3-software/MaCh3Tutorial.git MaCh3Validations

    - name: Setup virtual env
      working-directory: /opt/MaCh3Validations
      run: |
        pip install virtualenv
        virtualenv .venv 
        source .venv/bin/activate
        pip install --upgrade pip
        pip install numpy

    - name: Install pytest
      env: 
        CMAKE_ARGS: "-DPYTHON_ENABLED=ON -DMaCh3_Branch=${{ github.head_ref }}"

      working-directory: /opt/MaCh3Validations
      run: |
        source .venv/bin/activate
        pip install -v ".[testing]"
      
    - name: Validations
      working-directory: /opt/MaCh3Validations
      run: |
        source .venv/bin/activate
        export MACH3=$PWD
        source "$ROOTSYS/bin/thisroot.sh"
        pytest --config TutorialConfigs/FitterConfig.yaml CIValidations/PythonTests
        
