---
name: Post MaCh3 Newsletter
on:
  schedule:
    - cron: '0 0 * * 1' # Every Monday at midnight

jobs:
  post_discussion:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0

      - name: MaCh3 stats
        uses: ./.github/actions/mach3-stats
        with:
          repository: mach3-software/MaCh3
          prefix: mach3
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: MaCh3Tutorial stats
        uses: ./.github/actions/mach3-stats
        with:
          repository: mach3-software/MaCh3Tutorial
          prefix: tutorial
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: MaCh3SbiTools stats
        uses: ./.github/actions/mach3-stats
        with:
          repository: mach3-software/MaCh3SbiTools
          prefix: sbi
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set date
        run: echo "current_date=$(date +'%d/%m/%Y')" >> "$GITHUB_ENV"

      - name: Create a new GitHub Discussion
        uses: abirismyname/create-discussion@6e6ef67e5eeb042343ef8b3d8d0f5d545cbdf024  # v1.2.0
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: MaCh3 Newsletter 📰 - ${{ env.current_date }}
          body: |
            It's-a me, MaChio! Welcome to the newsletter.

            Date: ${{ env.current_date }}

            **MaCh3 Repository**
            - Total number of commits: ${{ env.mach3_commit_count }}
            - Total number of commits in the last week: ${{ env.mach3_commits_last_week }}
            - Most recent tag: ${{ env.mach3_latest_tag }}
            - Most active author in the last week: ${{ env.mach3_most_active_author_name }} (Commits: ${{ env.mach3_most_active_author_count }})
            - Author with most PRs last week: ${{ env.mach3_most_active_pr_author_name }} (PRs: ${{ env.mach3_most_active_pr_author_count }})
            - Number of PR last week is ${{ env.mach3_number_of_PR }}

            **MaCh3 Tutorial Repository**
            - Total number of commits: ${{ env.tutorial_commit_count }}
            - Total number of commits in the last week: ${{ env.tutorial_commits_last_week }}
            - Most recent tag: ${{ env.tutorial_latest_tag }}
            - Most active author in the last week: ${{ env.tutorial_most_active_author_name }} (Commits: ${{ env.tutorial_most_active_author_count }})
            - Author with most PRs last week: ${{ env.tutorial_most_active_pr_author_name }} (PRs: ${{ env.tutorial_most_active_pr_author_count }})
            - Number of PR last week is ${{ env.tutorial_number_of_PR }}

            **MaCh3 SbiTools Repository**
            - Total number of commits: ${{ env.sbi_commit_count }}
            - Total number of commits in the last week: ${{ env.sbi_commits_last_week }}
            - Most recent tag: ${{ env.sbi_latest_tag }}
            - Most active author in the last week: ${{ env.sbi_most_active_author_name }} (Commits: ${{ env.sbi_most_active_author_count }})
            - Author with most PRs last week: ${{ env.sbi_most_active_pr_author_name }} (PRs: ${{ env.sbi_most_active_pr_author_count }})
            - Number of PR last week is ${{ env.sbi_number_of_PR }}

            Cheers,
            MaCh3-bot

          repository-id: MDEwOlJlcG9zaXRvcnkzMzEwNDk0MTY=
          category-id: DIC_kwDOE7tpyM4CgQ7H
