name: "PR Title Checker"
on: [pull_request_target]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:

      - name: Debug PR context
        run: |
          echo "Pull request event: GRUMPY"
          echo "PR title: GRUMPY"

      - uses: actions/checkout@v3


