---
# Squash some branches
name: Squash CI

# The events that trigger the workflow
on:
  schedule:
    - cron: '0 12 1 * *'  # Runs at 12:00 GMT (UTC) on the 1st day of every month

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # KS: Prevents cancellation of remaining jobs if one fails
      matrix:
        include:
          - branch_name: gh-pages
          - branch_name: gh-profiling
          - branch_name: gh-pages-archive

    name: Squash CI ${{ matrix.branch_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0

      - name: Squash commits
        uses: ./.github/actions/squash
        with:
          branch: ${{ matrix.branch_name }}
