---
# This will run telemetry like RAM etc and make summary
name: MaCh3 Telemetry

on:
  pull_request:
    branches: [ develop ]

permissions:
  issues: write
  pull-requests: write

jobs:
  benchmark:
    name: Telemetry
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mach3-software/mach3:alma9v1.3.0
    steps:
      - name: Get MaCh3 Validations
        run: |
          cd /opt/
          # Clone the MaCh3Tutorial repository with the current branch
          git clone --branch main https://github.com/mach3-software/MaCh3Tutorial.git MaCh3Validations
          cd MaCh3Validations
          mkdir build
          cd build
          cmake ../ -DMaCh3_Branch=${{ github.head_ref }}

      - name: Build MaCh3 Validations
        run: |
          cd /opt/MaCh3Validations/build
          make -j4 install # Build and install the project

      - name: Run memory telemetry and generate plot
        run: |
          cd /opt/MaCh3Validations/build
          find -iname "RAM.sh"
          ./_deps/mach3-src/.github/CIscripts/RAM.sh

      - name: Upload memory usage plot as artifact
        id: upload
        if: success()
        run: |
          mkdir -p "$GITHUB_WORKSPACE/artifacts"
          cp /opt/MaCh3Validations/build/memory_usage_plot.png "$GITHUB_WORKSPACE/artifacts/"
          echo "::set-output name=image_path::$GITHUB_WORKSPACE/artifacts/memory_usage_plot.png"

      - name: Print image link to job summary
        run: |
          echo "### Memory Usage Plot" >> $GITHUB_STEP_SUMMARY
          echo "![Memory Usage Plot](${{ steps.upload.outputs.image_path }})" >> $GITHUB_STEP_SUMMARY

      - name: Create PR comment with summary link
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            You can view the memory usage plot in the job summary: [Job Summary Link](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
